### ISSUE TITLE
Group Activities

### ISSUE THREAD

**Issue by junpingfu** [FlipByBlink/PersonaChess#1]
Do Group Activities require an Apple developer account type of company to be used？

**Comment by FlipByBlink** [comment]
Sorry, I don't really know the details about that.

**Comment by junpingfu** [comment]
Is the PersonaChess app you posted using a personal developer account？

**Comment by FlipByBlink** [comment]
Yes, it is my personal account that is registered with Apple Developer Program.

**Comment by junpingfu** [comment]
OK, Thinks you
