### ISSUE TITLE
Question test

### ISSUE THREAD

**Issue by gregoireLem** [FlipByBlink/PersonaChess#3]
Thanks for the repo !
Does the 2 Vision Pro needs the app in order to both be able to interact with the pieces ?

**Comment by FlipByBlink** [comment]
Yes.

To debug SharePlay, two Apple Vision Pros are required. SharePlay does not work in simulator.

**Comment by gregoireLem** [comment]
Yes but the app should be install in both, right ?
It’s not possible to only install on 1 then use shareplay ?

Le dim. 19 mai 2024 à 00:04, Ryo Yamashita ***@***.***> a
écrit :

**Comment by FlipByBlink** [comment]
Yes. The app must be installed on both devices.

Please use TestFlight to install the app on someone else's Apple Vision Pro.

**Comment by gregoireLem** [comment]
Thanks 🫡
